// AUTO-GENERATED by scripts/generate-env.js — do not edit manually.
// Source of truth: environment variables at build time (see vercel.json / Vercel dashboard).
export const environment = {
  production: true,
  authBypass: false,
  apiBaseUrl: '/api/v1',
  cardServiceUrl: '/card-svc',
  keycloak: {
    url: 'https://auth.cba.com',
    realm: 'cba',
    clientId: 'cba-web',
  },
};
