import { Routes } from '@angular/router';
import { UsersComponent } from './users';
import { RolesComponent } from './roles';
import { OfficesComponent } from './offices';
import { OpenBankingComponent } from './open-banking';
import { HooksComponent } from './hooks';
import { MakerCheckerComponent } from './maker-checker';
import { NotificationsComponent } from './notifications';
import { AuditLogComponent } from './audit-log';
import { SmsCampaignsComponent } from './sms-campaigns';
import { StaffComponent } from './staff';
import { StandingInstructionsComponent } from './standing-instructions';
import { LoginHistoryComponent } from './login-history';
import { ComplianceReportComponent } from './compliance-report';
import { BulkImportComponent } from './bulk-import';
import { SecurityPolicyComponent } from './security-policy';
import { FraudAlertsComponent } from './fraud-alerts';
import { FraudCasesComponent } from './fraud-cases';
import { BlacklistComponent } from './blacklist';
import { FraudRulesAdminComponent } from './fraud-rules-admin';

export const ADMIN_ROUTES: Routes = [
  { path: 'users', component: UsersComponent },
  { path: 'roles', component: RolesComponent },
  { path: 'offices', component: OfficesComponent },
  { path: 'staff', component: StaffComponent },
  { path: 'open-banking', component: OpenBankingComponent },
  { path: 'hooks', component: HooksComponent },
  { path: 'maker-checker', component: MakerCheckerComponent },
  { path: 'notifications', component: NotificationsComponent },
  { path: 'audit-log', component: AuditLogComponent },
  { path: 'sms-campaigns', component: SmsCampaignsComponent },
  { path: 'standing-instructions', component: StandingInstructionsComponent },
  { path: 'login-history', component: LoginHistoryComponent },
  { path: 'compliance', component: ComplianceReportComponent },
  { path: 'bulk-import', component: BulkImportComponent },
  { path: 'security-policy', component: SecurityPolicyComponent },
  { path: 'fraud-alerts', component: FraudAlertsComponent },
  { path: 'fraud-cases', component: FraudCasesComponent },
  { path: 'blacklist', component: BlacklistComponent },
  { path: 'fraud-rules', component: FraudRulesAdminComponent },
];
