import { Routes } from '@angular/router';
import { CodesComponent } from './codes';
import { GlobalConfigComponent } from './global-config';
import { FloatingRatesComponent } from './floating-rates';
import { TaxesComponent } from './taxes';
import { AccountAlgorithmsComponent } from './account-algorithms';
import { HolidaysComponent } from './holidays';
import { PaymentTypesComponent } from './payment-types';
import { ExchangeRatesComponent } from './exchange-rates';
import { FundsComponent } from './funds';
import { AccountNumberFormatsComponent } from './account-number-formats';
import { DataTablesComponent } from './datatables';
import { SurveysComponent } from './surveys';
import { CreditBureauComponent } from './credit-bureau';
import { FieldConfigurationComponent } from './field-configuration';

export const SYSTEM_ROUTES: Routes = [
  { path: 'codes', component: CodesComponent },
  { path: 'config', component: GlobalConfigComponent },
  { path: 'floating-rates', component: FloatingRatesComponent },
  { path: 'taxes', component: TaxesComponent },
  { path: 'account-algorithms', component: AccountAlgorithmsComponent },
  { path: 'holidays', component: HolidaysComponent },
  { path: 'payment-types', component: PaymentTypesComponent },
  { path: 'exchange-rates', component: ExchangeRatesComponent },
  { path: 'funds', component: FundsComponent },
  { path: 'account-number-formats', component: AccountNumberFormatsComponent },
  { path: 'datatables', component: DataTablesComponent },
  { path: 'surveys', component: SurveysComponent },
  { path: 'credit-bureau', component: CreditBureauComponent },
  { path: 'field-configuration', component: FieldConfigurationComponent },
];
