#!/usr/bin/env node
/**
 * Generates src/environments/environment.prod.ts from process.env at build time.
 * Called automatically via the `prebuild` npm lifecycle hook before `ng build`.
 * On Vercel, env vars are set in the project settings and injected here.
 * Locally (no env vars set), safe defaults are used.
 */
const fs = require('fs');
const path = require('path');

const authBypass  = process.env.NG_APP_AUTH_BYPASS === 'true';
const apiUrl      = process.env.NG_APP_API_URL          || '/api/v1';
const kcUrl       = process.env.NG_APP_KEYCLOAK_URL     || 'https://auth.cba.com';
const kcRealm     = process.env.NG_APP_KEYCLOAK_REALM   || 'cba';
const kcClientId  = process.env.NG_APP_KEYCLOAK_CLIENT_ID || 'cba-web';

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit manually.
// Source of truth: environment variables at build time (see vercel.json / Vercel dashboard).
export const environment = {
  production: true,
  authBypass: ${authBypass},
  apiBaseUrl: '${apiUrl}',
  keycloak: {
    url: '${kcUrl}',
    realm: '${kcRealm}',
    clientId: '${kcClientId}',
  },
};
`;

const outPath = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log(`[generate-env] authBypass=${authBypass} apiBaseUrl=${apiUrl} keycloak.url=${kcUrl}`);
