package com.cba.fep.emv;

import com.cba.fep.hsm.HsmAdapter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.bouncycastle.crypto.BlockCipher;
import org.bouncycastle.crypto.engines.DESedeEngine;
import org.bouncycastle.crypto.engines.SM4Engine;
import org.bouncycastle.crypto.macs.CBCBlockCipherMac;
import org.bouncycastle.crypto.params.KeyParameter;
import org.springframework.stereotype.Component;

import java.util.Arrays;

/**
 * EMV ARQC (Application Request Cryptogram) validator.
 *
 * <p>The ARQC is a CBC-MAC generated by the card's chip using a session key
 * derived from the Issuer Master Key (IMK) and the Application Transaction
 * Counter (ATC). The FEP validates the ARQC to confirm the transaction
 * originated from a genuine chip card.
 *
 * <h3>Supported cipher algorithms</h3>
 * <ul>
 *   <li>{@link CryptogramAlgorithm#TDES} — Triple-DES CBC-MAC per EMV Book 2 Annex A1.2.
 *       Used by Visa, Mastercard, Verve, Afrigo, and international UnionPay cards.</li>
 *   <li>{@link CryptogramAlgorithm#SM4} — SM4 CBC-MAC per PBOC 3.0 / GB/T 32918.
 *       Used by domestic China UnionPay (QPBOC) cards. SM4 is a 128-bit block cipher;
 *       structurally identical to the TDES flow but substitutes SM4Engine for DESedeEngine.</li>
 * </ul>
 *
 * <h3>Session key derivation (both algorithms)</h3>
 * <pre>
 *   SK_left  = Cipher(IMK_left,  ATC‖0xF0‖0x00‖ATC‖0x0F‖0x00)
 *   SK_right = Cipher(IMK_right, ATC‖0x0F‖0x00‖ATC‖0xF0‖0x00)
 *   SK = SK_left ‖ SK_right  (16 bytes)
 * </pre>
 *
 * <h3>Offline transaction handling</h3>
 * <p>VLP (Very Low Value Payment) contactless transactions may be approved offline
 * by the card. In that case the Cryptogram Information Data (CID tag {@code 9F27})
 * encodes an AC type of TC ({@code 0x40}) or AAC ({@code 0x00}) — not ARQC ({@code 0x80}).
 * Offline-decided transactions have no ARQC to validate; this validator detects them
 * and skips validation, returning {@code true} for TC (offline approved) and
 * {@code false} for AAC (offline declined).
 *
 * <p><strong>Dev note</strong>: Uses a hardcoded dev IMK. Production retrieves the
 * card's IMK from card-service (HSM-protected, per BIN range).
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class ArqcValidator {

    private final HsmAdapter hsmAdapter;

    // Dev IMK (Issuer Master Key) — replace with per-card HSM lookup in production
    private static final byte[] DEV_IMK = {
        (byte)0x01, (byte)0x23, (byte)0x45, (byte)0x67,
        (byte)0x89, (byte)0xAB, (byte)0xCD, (byte)0xEF,
        (byte)0xFE, (byte)0xDC, (byte)0xBA, (byte)0x98,
        (byte)0x76, (byte)0x54, (byte)0x32, (byte)0x10
    };

    // CID (tag 9F27) AC type bits (bits 7-6 of first byte)
    private static final byte CID_MASK       = (byte) 0xC0;
    private static final byte CID_AAC        = (byte) 0x00; // Offline declined — no ARQC
    private static final byte CID_TC         = (byte) 0x40; // Offline approved — no ARQC
    private static final byte CID_ARQC       = (byte) 0x80; // Online — ARQC present

    /**
     * Validate the ARQC using 3DES (default path — Visa, Mastercard, Verve, Afrigo,
     * international UnionPay).
     *
     * @param emvData parsed DE55 tags
     * @param pan     primary account number
     * @return {@code true} if ARQC is valid
     */
    public boolean validate(EmvData emvData, String pan) {
        return validate(emvData, pan, CryptogramAlgorithm.TDES);
    }

    /**
     * Validate the ARQC using the specified cipher algorithm.
     *
     * <p>For domestic China UnionPay cards, pass {@link CryptogramAlgorithm#SM4}.
     * All other schemes pass {@link CryptogramAlgorithm#TDES}.
     *
     * @param emvData   parsed DE55 tags
     * @param pan       primary account number
     * @param algorithm cipher algorithm for session key derivation and MAC computation
     * @return {@code true} if ARQC is valid (or offline TC is accepted), {@code false} otherwise
     */
    public boolean validate(EmvData emvData, String pan, CryptogramAlgorithm algorithm) {

        // ── Offline transaction detection ─────────────────────────────────────
        // Check the Cryptogram Information Data (CID, tag 9F27) for AC type.
        // VLP / contactless offline transactions carry a TC or AAC rather than ARQC.
        byte[] cid = emvData.getTag(EmvTag.CRYPTOGRAM_INFORMATION_DATA);
        if (cid != null && cid.length >= 1) {
            byte acType = (byte) (cid[0] & CID_MASK);
            if (acType == CID_TC) {
                // Offline approved — card committed the transaction without issuer involvement.
                // No ARQC to validate; accept the transaction.
                log.debug("ARQC validation skipped: CID=TC (offline approved)");
                return true;
            }
            if (acType == CID_AAC) {
                // Offline declined — card refused the transaction locally.
                log.debug("ARQC validation skipped: CID=AAC (offline declined — rejecting)");
                return false;
            }
            // CID_ARQC (0x80) falls through to online validation below
        }

        // ── Online ARQC validation ────────────────────────────────────────────
        byte[] arqc = emvData.getTag(EmvTag.ARQC);
        byte[] atc  = emvData.getTag(EmvTag.APPLICATION_TRANSACTION_COUNTER);

        if (arqc == null || atc == null) {
            log.warn("ARQC validation skipped: ARQC or ATC not present in DE55");
            return false;
        }

        try {
            byte[] sessionKey = deriveSessionKey(DEV_IMK, atc, algorithm);
            byte[] cryptData  = buildCryptogramData(emvData);
            byte[] computed   = computeCbcMac(sessionKey, cryptData, algorithm);

            // ARQC is the leftmost 8 bytes of the CBC-MAC output
            byte[] expectedArqc = Arrays.copyOf(computed, 8);
            boolean valid = Arrays.equals(arqc, expectedArqc);

            if (!valid && algorithm == CryptogramAlgorithm.SM4) {
                // International UnionPay cards may use 3DES even when scheme is UnionPay.
                // Fall back silently for the dev software path.
                log.debug("SM4 ARQC mismatch — retrying with TDES for international UnionPay");
                byte[] skTdes    = deriveSessionKey(DEV_IMK, atc, CryptogramAlgorithm.TDES);
                byte[] macTdes   = computeCbcMac(skTdes, cryptData, CryptogramAlgorithm.TDES);
                byte[] expectTdes = Arrays.copyOf(macTdes, 8);
                valid = Arrays.equals(arqc, expectTdes);
            }

            log.debug("ARQC validation [{}]: {} (ATC={})", algorithm,
                    valid ? "PASS" : "FAIL",
                    emvData.getTagHex(EmvTag.APPLICATION_TRANSACTION_COUNTER));
            return valid;

        } catch (Exception e) {
            log.error("ARQC validation error [{}]: {}", algorithm, e.getMessage());
            return false;
        }
    }

    // ── Session key derivation ────────────────────────────────────────────────

    /**
     * Derive the EMV session key.
     *
     * <p>The derivation data structure is identical for both TDES and SM4:
     * left half uses constants {@code 0xF0}/{@code 0x0F}, right half reverses them.
     * The only difference is which block cipher is used for the single-block encryption.
     */
    private byte[] deriveSessionKey(byte[] imk, byte[] atc, CryptogramAlgorithm algorithm)
            throws Exception {
        byte[] leftData  = new byte[8];
        byte[] rightData = new byte[8];

        // EMV Book 2 Annex A1.3 derivation constants
        leftData[0] = atc[0]; leftData[1] = atc[1];
        leftData[2] = (byte) 0xF0; leftData[3] = 0x00;
        leftData[4] = atc[0]; leftData[5] = atc[1];
        leftData[6] = (byte) 0x0F; leftData[7] = 0x00;

        rightData[0] = atc[0]; rightData[1] = atc[1];
        rightData[2] = (byte) 0x0F; rightData[3] = 0x00;
        rightData[4] = atc[0]; rightData[5] = atc[1];
        rightData[6] = (byte) 0xF0; rightData[7] = 0x00;

        byte[] skLeft;
        byte[] skRight;

        if (algorithm == CryptogramAlgorithm.SM4) {
            // SM4 uses the full 16-byte IMK directly as a single SM4 key.
            // Each derivation block is 8 bytes — SM4 has a 16-byte block size,
            // so we encrypt both halves concatenated in one ECB operation.
            byte[] derivInput = new byte[16];
            System.arraycopy(leftData,  0, derivInput, 0, 8);
            System.arraycopy(rightData, 0, derivInput, 8, 8);
            byte[] derivOutput = sm4EcbEncrypt(imk, derivInput);
            skLeft  = Arrays.copyOfRange(derivOutput, 0,  8);
            skRight = Arrays.copyOfRange(derivOutput, 8, 16);
        } else {
            // TDES: each 8-byte half is encrypted separately
            skLeft  = tripleDesEcb(imk, leftData);
            skRight = tripleDesEcb(imk, rightData);
        }

        byte[] sk = new byte[16];
        System.arraycopy(skLeft,  0, sk, 0, 8);
        System.arraycopy(skRight, 0, sk, 8, 8);
        return sk;
    }

    /**
     * Build the CDOL/UDOL cryptogram data block from EMV tags (EMV Book 2 Annex A1.2).
     * The same tag concatenation is used for both TDES and SM4.
     */
    private byte[] buildCryptogramData(EmvData emvData) {
        byte[][] parts = {
            emvData.getTag(EmvTag.AMOUNT_AUTHORISED),
            emvData.getTag(EmvTag.AMOUNT_OTHER),
            emvData.getTag(EmvTag.TRANSACTION_CURRENCY_CODE),
            emvData.getTag(EmvTag.TRANSACTION_DATE),
            emvData.getTag(EmvTag.TRANSACTION_TYPE),
            emvData.getTag(EmvTag.APPLICATION_TRANSACTION_COUNTER),
            emvData.getTag(EmvTag.TERMINAL_VERIFICATION_RESULTS),
        };

        int totalLen = 0;
        for (byte[] part : parts) {
            if (part != null) totalLen += part.length;
        }

        // ISO/IEC 7816-4 padding: 0x80 followed by 0x00 bytes to block boundary
        // TDES block = 8 bytes; SM4 block = 16 bytes — use 8-byte boundary for both
        // (SM4 CBC-MAC with Bouncy Castle pads internally; we pre-pad to 8 anyway)
        int paddedLen = ((totalLen + 7) / 8) * 8;
        byte[] data = new byte[paddedLen];
        int pos = 0;
        for (byte[] part : parts) {
            if (part != null) {
                System.arraycopy(part, 0, data, pos, part.length);
                pos += part.length;
            }
        }
        if (pos < paddedLen) {
            data[pos] = (byte) 0x80;
        }
        return data;
    }

    // ── Low-level cipher operations ───────────────────────────────────────────

    private byte[] computeCbcMac(byte[] key, byte[] data, CryptogramAlgorithm algorithm)
            throws Exception {
        BlockCipher engine;
        byte[] workKey;
        int macSizeBytes;

        if (algorithm == CryptogramAlgorithm.SM4) {
            // SM4: 128-bit key, 128-bit block; MAC = leftmost 8 bytes
            engine = new SM4Engine();
            workKey = key; // SM4 uses 16-byte key directly
            macSizeBytes = 8;
        } else {
            // TDES: extend 16-byte double-length key to 24-byte K1||K2||K1
            engine = new DESedeEngine();
            byte[] k24 = new byte[24];
            System.arraycopy(key, 0, k24, 0,  16);
            System.arraycopy(key, 0, k24, 16, 8);
            workKey = k24;
            macSizeBytes = 8;
        }

        CBCBlockCipherMac mac = new CBCBlockCipherMac(engine, macSizeBytes * 8);
        mac.init(new KeyParameter(workKey));
        mac.update(data, 0, data.length);
        byte[] result = new byte[macSizeBytes];
        mac.doFinal(result, 0);
        return result;
    }

    /** SM4-ECB single-pass encryption (for session key derivation). */
    private byte[] sm4EcbEncrypt(byte[] key, byte[] data) throws Exception {
        SM4Engine engine = new SM4Engine();
        engine.init(true, new KeyParameter(key));
        // SM4 has a 16-byte block size; data must be exactly 16 bytes for key derivation
        byte[] out = new byte[data.length];
        for (int i = 0; i + 16 <= data.length; i += 16) {
            engine.processBlock(data, i, out, i);
        }
        return out;
    }

    /** 3DES-ECB encryption of one 8-byte block (for TDES session key derivation). */
    private byte[] tripleDesEcb(byte[] key, byte[] data) throws Exception {
        javax.crypto.Cipher cipher = javax.crypto.Cipher.getInstance("DESede/ECB/NoPadding");
        byte[] k24 = new byte[24];
        System.arraycopy(key, 0, k24, 0, 16);
        System.arraycopy(key, 0, k24, 16, 8);
        cipher.init(javax.crypto.Cipher.ENCRYPT_MODE,
                new javax.crypto.spec.SecretKeySpec(k24, "DESede"));
        return cipher.doFinal(data);
    }
}
