package com.cba.fep.emv;

import com.cba.fep.hsm.HsmAdapter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.bouncycastle.crypto.engines.DESedeEngine;
import org.bouncycastle.crypto.macs.CBCBlockCipherMac;
import org.bouncycastle.crypto.params.KeyParameter;
import org.springframework.stereotype.Component;

import java.util.Arrays;

/**
 * EMV ARQC (Application Request Cryptogram) validator.
 *
 * <p>The ARQC is a 3DES MAC generated by the card's chip using the
 * Application Cryptogram (AC) session key derived from the card master key.
 * The FEP validates the ARQC to confirm the chip card generated the transaction.
 *
 * <p>Session key derivation (EMV Common Session Key Personalization):
 * <pre>
 *   SK_left  = 3DES(IMK_left, ATC || 0xF0 || ATC || 0x0F || PAN_right[8])
 *   SK_right = 3DES(IMK_right, ATC || 0x0F || ATC || 0xF0 || PAN_right[8])
 *   SK = SK_left || SK_right (16-byte double-length key)
 * </pre>
 *
 * <p>ARQC computation (EMV Book 2, Annex A1.2):
 * <pre>
 *   ARQC = CBC-MAC(SK, Amount || OtherAmount || TxnCurrency || TxnDate || TxnType ||
 *                      UDOL || ATC || IAD_indicator || TerminalCountry || TerminalCaps)
 * </pre>
 *
 * <p><strong>Dev note</strong>: In the software adapter, this validation uses
 * the hardcoded dev IMK. A production system must retrieve the card's IMK from
 * the card personalization bureau (HSM-protected key storage in card-service).
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class ArqcValidator {

    private final HsmAdapter hsmAdapter;

    // Dev IMK (Issuer Master Key) — same as SoftwareHsmAdapter.DEV_PIN_KEY conceptually
    // Production: loaded from card-service per BIN range
    private static final byte[] DEV_IMK = {
        (byte)0x01, (byte)0x23, (byte)0x45, (byte)0x67,
        (byte)0x89, (byte)0xAB, (byte)0xCD, (byte)0xEF,
        (byte)0xFE, (byte)0xDC, (byte)0xBA, (byte)0x98,
        (byte)0x76, (byte)0x54, (byte)0x32, (byte)0x10
    };

    /**
     * Validate the ARQC in the parsed EMV data.
     *
     * @param emvData parsed DE55 tags
     * @param pan     primary account number
     * @return {@code true} if ARQC is cryptographically valid
     */
    public boolean validate(EmvData emvData, String pan) {
        byte[] arqc = emvData.getTag(EmvTag.ARQC);
        byte[] atc  = emvData.getTag(EmvTag.APPLICATION_TRANSACTION_COUNTER);
        byte[] iad  = emvData.getTag(EmvTag.ISSUER_APPLICATION_DATA);

        if (arqc == null || atc == null) {
            log.warn("ARQC validation skipped: ARQC or ATC not present in DE55");
            return false;
        }

        try {
            byte[] sessionKey = deriveSessionKey(DEV_IMK, atc, pan);
            byte[] cryptData  = buildCryptogramData(emvData);
            byte[] computed   = computeCbcMac(sessionKey, cryptData);

            // ARQC is leftmost 8 bytes of CBC-MAC
            byte[] expectedArqc = Arrays.copyOf(computed, 8);
            boolean valid = Arrays.equals(arqc, expectedArqc);

            log.debug("ARQC validation: {} (ATC={})", valid ? "PASS" : "FAIL",
                    emvData.getTagHex(EmvTag.APPLICATION_TRANSACTION_COUNTER));
            return valid;
        } catch (Exception e) {
            log.error("ARQC validation error: {}", e.getMessage());
            return false;
        }
    }

    /**
     * Derive EMV session key from Issuer Master Key + ATC.
     * EMV Common Session Key Personalization method (Book 2, Annex A1.3).
     */
    private byte[] deriveSessionKey(byte[] imk, byte[] atc, String pan) throws Exception {
        // Session key derivation data: ATC + derivation constants
        byte[] leftData  = new byte[8];
        byte[] rightData = new byte[8];

        leftData[0] = atc[0];
        leftData[1] = atc[1];
        leftData[2] = (byte) 0xF0;
        leftData[3] = 0x00;
        leftData[4] = atc[0];
        leftData[5] = atc[1];
        leftData[6] = (byte) 0x0F;
        leftData[7] = 0x00;

        rightData[0] = atc[0];
        rightData[1] = atc[1];
        rightData[2] = (byte) 0x0F;
        rightData[3] = 0x00;
        rightData[4] = atc[0];
        rightData[5] = atc[1];
        rightData[6] = (byte) 0xF0;
        rightData[7] = 0x00;

        byte[] skLeft  = tripleDesEcb(imk, leftData);
        byte[] skRight = tripleDesEcb(imk, rightData);

        byte[] sk = new byte[16];
        System.arraycopy(skLeft,  0, sk, 0, 8);
        System.arraycopy(skRight, 0, sk, 8, 8);
        return sk;
    }

    /**
     * Build the cryptogram data block from EMV tags per Book 2 Annex A1.2.
     * Order: Amount Authorised + Amount Other + TxnCurrencyCode + TxnDate + TxnType
     *        + ATC + IAD (if present, first byte only as indicator)
     */
    private byte[] buildCryptogramData(EmvData emvData) {
        byte[][] parts = {
            emvData.getTag(EmvTag.AMOUNT_AUTHORISED),
            emvData.getTag(EmvTag.AMOUNT_OTHER),
            emvData.getTag(EmvTag.TRANSACTION_CURRENCY_CODE),
            emvData.getTag(EmvTag.TRANSACTION_DATE),
            emvData.getTag(EmvTag.TRANSACTION_TYPE),
            emvData.getTag(EmvTag.APPLICATION_TRANSACTION_COUNTER),
            emvData.getTag(EmvTag.TERMINAL_VERIFICATION_RESULTS),
        };

        int totalLen = 0;
        for (byte[] part : parts) {
            if (part != null) totalLen += part.length;
        }

        // Pad to 8-byte boundary with 0x80 0x00...
        int paddedLen = ((totalLen + 7) / 8) * 8;
        byte[] data = new byte[paddedLen];
        int pos = 0;
        for (byte[] part : parts) {
            if (part != null) {
                System.arraycopy(part, 0, data, pos, part.length);
                pos += part.length;
            }
        }
        if (pos < paddedLen) {
            data[pos] = (byte) 0x80; // ISO/IEC 7816-4 padding
        }
        return data;
    }

    private byte[] computeCbcMac(byte[] key, byte[] data) throws Exception {
        // Extend 16-byte key to 24-byte 3DES key (K1||K2||K1)
        byte[] k24 = new byte[24];
        System.arraycopy(key, 0,  k24, 0,  16);
        System.arraycopy(key, 0,  k24, 16, 8);

        DESedeEngine engine = new DESedeEngine();
        CBCBlockCipherMac mac = new CBCBlockCipherMac(engine, 64);
        mac.init(new KeyParameter(k24));
        mac.update(data, 0, data.length);
        byte[] result = new byte[8];
        mac.doFinal(result, 0);
        return result;
    }

    private byte[] tripleDesEcb(byte[] key, byte[] data) throws Exception {
        javax.crypto.Cipher cipher = javax.crypto.Cipher.getInstance("DESede/ECB/NoPadding");
        // Extend 16-byte key to 24-byte
        byte[] k24 = new byte[24];
        System.arraycopy(key, 0, k24, 0, 16);
        System.arraycopy(key, 0, k24, 16, 8);
        cipher.init(javax.crypto.Cipher.ENCRYPT_MODE,
                new javax.crypto.spec.SecretKeySpec(k24, "DESede"));
        return cipher.doFinal(data);
    }
}
