-- ═══════════════════════════════════════════════════════════════════
-- V1__init_schema.sql — CBA Core Banking Platform
-- All monetary values: NUMERIC(19,4) → BigDecimal in Java
-- All UUIDs generated by PostgreSQL gen_random_uuid()
-- Optimistic locking: version BIGINT on every mutable table
-- Multi-tenancy: tenant_id nullable in v1 (required in v2)
-- ═══════════════════════════════════════════════════════════════════

-- ── Extensions ──────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── tenants (stub for multi-tenancy in v2) ──────────────────────────
CREATE TABLE tenants (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(20) UNIQUE NOT NULL,
    name        VARCHAR(100) NOT NULL,
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── loan_products ────────────────────────────────────────────────────
CREATE TABLE loan_products (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID            REFERENCES tenants(id),
    name                VARCHAR(100)    NOT NULL,
    description         TEXT,
    currency_code       CHAR(3)         NOT NULL DEFAULT 'USD',
    min_principal       NUMERIC(19,4)   NOT NULL,
    max_principal       NUMERIC(19,4)   NOT NULL,
    min_interest_rate   NUMERIC(8,4)    NOT NULL,
    max_interest_rate   NUMERIC(8,4)    NOT NULL,
    default_interest_rate NUMERIC(8,4)  NOT NULL,
    min_term_months     INT             NOT NULL,
    max_term_months     INT             NOT NULL,
    repayment_type      VARCHAR(30)     NOT NULL DEFAULT 'ANNUITY',
    origination_fee     NUMERIC(19,4)   NOT NULL DEFAULT 0,
    late_payment_fee    NUMERIC(19,4)   NOT NULL DEFAULT 0,
    active              BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version             BIGINT          NOT NULL DEFAULT 0
);

-- ── deposit_products ─────────────────────────────────────────────────
CREATE TABLE deposit_products (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               UUID            REFERENCES tenants(id),
    name                    VARCHAR(100)    NOT NULL,
    description             TEXT,
    account_type            VARCHAR(30)     NOT NULL,
    currency_code           CHAR(3)         NOT NULL DEFAULT 'USD',
    minimum_balance         NUMERIC(19,4)   NOT NULL DEFAULT 0,
    interest_rate           NUMERIC(8,4)    NOT NULL DEFAULT 0,
    interest_compounding    VARCHAR(20)     NOT NULL DEFAULT 'MONTHLY',
    active                  BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version                 BIGINT          NOT NULL DEFAULT 0
);

-- ── customers ────────────────────────────────────────────────────────
CREATE TABLE customers (
    id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               UUID        REFERENCES tenants(id),
    external_id             VARCHAR(50) UNIQUE NOT NULL,
    -- All PII stored AES-256 encrypted via JPA AttributeConverter
    first_name_encrypted    TEXT        NOT NULL,
    last_name_encrypted     TEXT        NOT NULL,
    email_encrypted         TEXT        NOT NULL,
    phone_encrypted         TEXT,
    national_id_encrypted   TEXT,
    date_of_birth           DATE,
    kyc_status              VARCHAR(20) NOT NULL DEFAULT 'PENDING_KYC',
    -- PENDING_KYC | ACTIVE | SUSPENDED | CLOSED
    notes                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by              VARCHAR(100),
    updated_by              VARCHAR(100),
    version                 BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX idx_customers_kyc_status ON customers(kyc_status);
CREATE INDEX idx_customers_tenant     ON customers(tenant_id);

-- ── accounts ─────────────────────────────────────────────────────────
CREATE TABLE accounts (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID            REFERENCES tenants(id),
    account_number  VARCHAR(25)     UNIQUE NOT NULL,
    -- Format: {branch_code}-{type_code}-{sequence} e.g. 001-SAV-0001234
    customer_id     UUID            NOT NULL REFERENCES customers(id),
    product_id      UUID            NOT NULL REFERENCES deposit_products(id),
    account_type    VARCHAR(30)     NOT NULL,
    -- SAVINGS | CHECKING | FIXED_DEPOSIT
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    -- ACTIVE | FROZEN | DORMANT | CLOSED
    balance         NUMERIC(19,4)   NOT NULL DEFAULT 0,
    currency_code   CHAR(3)         NOT NULL DEFAULT 'USD',
    opened_date     DATE            NOT NULL DEFAULT CURRENT_DATE,
    closed_date     DATE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    version         BIGINT          NOT NULL DEFAULT 0
);

CREATE INDEX idx_accounts_customer   ON accounts(customer_id);
CREATE INDEX idx_accounts_status     ON accounts(status);
CREATE INDEX idx_accounts_tenant     ON accounts(tenant_id);

-- ── transactions (immutable — never update or delete) ─────────────────
CREATE TABLE transactions (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID            REFERENCES tenants(id),
    account_id          UUID            NOT NULL REFERENCES accounts(id),
    transaction_type    VARCHAR(30)     NOT NULL,
    -- DEPOSIT | WITHDRAWAL | TRANSFER_DEBIT | TRANSFER_CREDIT
    -- LOAN_DISBURSEMENT | LOAN_REPAYMENT | INTEREST_CREDIT | FEE_CHARGE
    amount              NUMERIC(19,4)   NOT NULL,
    running_balance     NUMERIC(19,4)   NOT NULL,
    currency_code       CHAR(3)         NOT NULL DEFAULT 'USD',
    description         TEXT,
    reference_number    VARCHAR(50),
    payment_id          UUID,
    transaction_date    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    value_date          DATE            NOT NULL DEFAULT CURRENT_DATE,
    created_by          VARCHAR(100)
);

CREATE INDEX idx_transactions_account ON transactions(account_id);
CREATE INDEX idx_transactions_date    ON transactions(transaction_date DESC);
CREATE INDEX idx_transactions_ref     ON transactions(reference_number);

-- ── loans ─────────────────────────────────────────────────────────────
CREATE TABLE loans (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               UUID            REFERENCES tenants(id),
    loan_account_number     VARCHAR(25)     UNIQUE NOT NULL,
    customer_id             UUID            NOT NULL REFERENCES customers(id),
    product_id              UUID            NOT NULL REFERENCES loan_products(id),
    linked_account_id       UUID            REFERENCES accounts(id),
    -- Account to disburse into / collect from
    principal_amount        NUMERIC(19,4)   NOT NULL,
    approved_amount         NUMERIC(19,4),
    outstanding_balance     NUMERIC(19,4),
    interest_rate           NUMERIC(8,4)    NOT NULL,
    term_months             INT             NOT NULL,
    status                  VARCHAR(40)     NOT NULL DEFAULT 'SUBMITTED',
    -- SUBMITTED | UNDER_REVIEW | APPROVED | DISBURSED | ACTIVE
    -- IN_ARREARS | CLOSED_OBLIGATIONS_MET | WRITTEN_OFF
    application_date        DATE            NOT NULL DEFAULT CURRENT_DATE,
    approval_date           DATE,
    disbursement_date       DATE,
    maturity_date           DATE,
    approved_by             VARCHAR(100),
    notes                   TEXT,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              VARCHAR(100),
    updated_by              VARCHAR(100),
    version                 BIGINT          NOT NULL DEFAULT 0
);

CREATE INDEX idx_loans_customer  ON loans(customer_id);
CREATE INDEX idx_loans_status    ON loans(status);
CREATE INDEX idx_loans_tenant    ON loans(tenant_id);

-- ── loan_repayment_schedule ───────────────────────────────────────────
CREATE TABLE loan_repayment_schedule (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    loan_id         UUID            NOT NULL REFERENCES loans(id),
    installment_no  INT             NOT NULL,
    due_date        DATE            NOT NULL,
    principal_due   NUMERIC(19,4)   NOT NULL,
    interest_due    NUMERIC(19,4)   NOT NULL,
    fees_due        NUMERIC(19,4)   NOT NULL DEFAULT 0,
    total_due       NUMERIC(19,4)   NOT NULL,
    principal_paid  NUMERIC(19,4)   NOT NULL DEFAULT 0,
    interest_paid   NUMERIC(19,4)   NOT NULL DEFAULT 0,
    fees_paid       NUMERIC(19,4)   NOT NULL DEFAULT 0,
    total_paid      NUMERIC(19,4)   NOT NULL DEFAULT 0,
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    -- PENDING | PAID | PARTIALLY_PAID | OVERDUE | WAIVED
    paid_date       DATE,
    UNIQUE (loan_id, installment_no)
);

CREATE INDEX idx_repayment_loan     ON loan_repayment_schedule(loan_id);
CREATE INDEX idx_repayment_due_date ON loan_repayment_schedule(due_date);
CREATE INDEX idx_repayment_status   ON loan_repayment_schedule(status);

-- ── payments ─────────────────────────────────────────────────────────
CREATE TABLE payments (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               UUID            REFERENCES tenants(id),
    reference_number        VARCHAR(50)     UNIQUE NOT NULL,
    payment_type            VARCHAR(30)     NOT NULL,
    -- INTERNAL_TRANSFER | EXTERNAL_PAYMENT | STANDING_ORDER | BILL_PAYMENT
    source_account_id       UUID            REFERENCES accounts(id),
    destination_account_id  UUID            REFERENCES accounts(id),
    amount                  NUMERIC(19,4)   NOT NULL,
    currency_code           CHAR(3)         NOT NULL DEFAULT 'USD',
    description             TEXT,
    status                  VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    -- PENDING | PROCESSING | COMPLETED | FAILED | REVERSED
    scheduled_date          DATE,
    executed_date           TIMESTAMPTZ,
    failure_reason          TEXT,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              VARCHAR(100),
    version                 BIGINT          NOT NULL DEFAULT 0
);

CREATE INDEX idx_payments_source      ON payments(source_account_id);
CREATE INDEX idx_payments_destination ON payments(destination_account_id);
CREATE INDEX idx_payments_status      ON payments(status);
CREATE INDEX idx_payments_ref         ON payments(reference_number);

-- ── standing_orders ───────────────────────────────────────────────────
CREATE TABLE standing_orders (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               UUID            REFERENCES tenants(id),
    source_account_id       UUID            NOT NULL REFERENCES accounts(id),
    destination_account_id  UUID            NOT NULL REFERENCES accounts(id),
    amount                  NUMERIC(19,4)   NOT NULL,
    currency_code           CHAR(3)         NOT NULL DEFAULT 'USD',
    frequency               VARCHAR(20)     NOT NULL,
    -- WEEKLY | MONTHLY | QUARTERLY | ANNUALLY
    next_execution_date     DATE            NOT NULL,
    end_date                DATE,
    description             TEXT,
    active                  BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version                 BIGINT          NOT NULL DEFAULT 0
);

-- ── open_banking_consents ─────────────────────────────────────────────
CREATE TABLE open_banking_consents (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID        REFERENCES tenants(id),
    consent_id      VARCHAR(50) UNIQUE NOT NULL,
    customer_id     UUID        NOT NULL REFERENCES customers(id),
    tpp_client_id   VARCHAR(100) NOT NULL,
    status          VARCHAR(30) NOT NULL DEFAULT 'AWAITING_AUTHORISATION',
    -- AWAITING_AUTHORISATION | AUTHORISED | REVOKED | EXPIRED
    expiry_date     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE consent_scopes (
    consent_id  UUID        NOT NULL REFERENCES open_banking_consents(id),
    scope       VARCHAR(100) NOT NULL
);

CREATE INDEX idx_consents_customer ON open_banking_consents(customer_id);
CREATE INDEX idx_consents_status   ON open_banking_consents(status);
CREATE INDEX idx_consent_scopes    ON consent_scopes(consent_id);

-- ── audit_log (append-only — NEVER UPDATE OR DELETE) ─────────────────
CREATE TABLE audit_log (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID        REFERENCES tenants(id),
    entity_type VARCHAR(100) NOT NULL,
    entity_id   VARCHAR(100) NOT NULL,
    action      VARCHAR(50) NOT NULL,
    changed_by  VARCHAR(100) NOT NULL,
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    old_values  JSONB,
    new_values  JSONB,
    ip_address  INET,
    user_agent  TEXT,
    session_id  VARCHAR(100)
);

CREATE INDEX idx_audit_entity  ON audit_log(entity_type, entity_id);
CREATE INDEX idx_audit_time    ON audit_log(changed_at DESC);
CREATE INDEX idx_audit_user    ON audit_log(changed_by);

-- ── account_number_sequences (for deterministic account numbers) ──────
CREATE TABLE account_number_sequences (
    branch_code VARCHAR(10) NOT NULL,
    account_type VARCHAR(10) NOT NULL,
    last_sequence BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (branch_code, account_type)
);

INSERT INTO account_number_sequences (branch_code, account_type)
VALUES ('001', 'SAV'), ('001', 'CHK'), ('001', 'FXD'), ('001', 'LN');
