package com.cba.fep.scheme;

import com.cba.fep.auth.AuthorizationResult;
import com.cba.fep.emv.CryptogramAlgorithm;
import org.jpos.iso.ISOException;
import org.jpos.iso.ISOMsg;

/**
 * Pluggable scheme adapter interface.
 *
 * <p>Each card scheme (Visa, Mastercard, Verve, Afrigo, UnionPay) implements
 * this interface to handle scheme-specific message processing. The FEP core
 * treats all schemes identically — scheme differentiation is isolated here.
 *
 * <p>Responsibilities of a scheme adapter:
 * <ul>
 *   <li>Apply the scheme's ISO 8583 packager to the message</li>
 *   <li>Parse scheme-specific private DEs (DE 48, DE 60–63, DE 111–127)</li>
 *   <li>Populate scheme-specific fields in authorization requests</li>
 *   <li>Embed ARPC / cryptographic response data in the response message</li>
 *   <li>Perform scheme-specific response finalization (routing flags, etc.)</li>
 * </ul>
 */
public interface SchemeAdapter {

    /** The scheme this adapter handles. */
    SchemeType getSchemeType();

    /**
     * Apply the scheme-specific packager to the message so that
     * private DEs can be correctly packed/unpacked.
     */
    void applyPackager(ISOMsg msg) throws ISOException;

    /**
     * Extract scheme-specific private data from inbound DE fields.
     * Called after unpacking, before forwarding to card-service.
     *
     * @return parsed scheme data as an opaque string map (adapter-defined keys)
     */
    java.util.Map<String, String> extractPrivateData(ISOMsg msg) throws ISOException;

    /**
     * Embed the ARPC (Authorization Response Cryptogram) into the
     * response message's ICC data field (DE55).
     *
     * @param response outbound 0110 response message
     * @param arpc     ARPC bytes generated by {@link com.cba.fep.emv.ArpcGenerator}
     */
    void embedArpc(ISOMsg response, byte[] arpc) throws ISOException;

    /**
     * Apply scheme-specific finalization to an outbound response.
     * Examples: populate Visa DE63 STIP flags, Mastercard PDS tokens, etc.
     */
    void finalizeResponse(ISOMsg response, AuthorizationResult result, SchemeType scheme)
            throws ISOException;

    /**
     * The cryptogram algorithm used by this scheme for ARQC/ARPC computation.
     *
     * <p>Defaults to {@link CryptogramAlgorithm#TDES} — the EMV Book 2 standard used by
     * Visa, Mastercard, Verve, Afrigo, and international UnionPay cards.
     *
     * <p>{@link com.cba.fep.scheme.UnionPaySchemeAdapter} overrides this to
     * {@link CryptogramAlgorithm#SM4} for domestic China QPBOC cards.
     *
     * @return the algorithm to use when validating the ARQC from this scheme's cards
     */
    default CryptogramAlgorithm getCryptogramAlgorithm() {
        return CryptogramAlgorithm.TDES;
    }
}
