-- ============================================================
-- CBA Card Service — V4 3D Secure ACS Module
-- ============================================================
-- Tables:
--   threeds_sessions  — one per authentication attempt (AReq lifecycle)
--   threeds_otp_tokens — OTP codes for challenge-based authentication
-- ============================================================

-- ── 3DS Sessions ──────────────────────────────────────────────────────────────
-- Tracks the full lifecycle of a 3DS authentication attempt from AReq receipt
-- through cardholder authentication to CAVV generation.
--
-- Status flow:
--   INITIATED → CHALLENGE_REQUIRED → AUTHENTICATED
--   INITIATED → AUTHENTICATED (frictionless — no challenge step)
--   INITIATED → FAILED | REJECTED
CREATE TABLE threeds_sessions (
    id                       UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    card_id                  UUID         REFERENCES cards(id),
    merchant_id              VARCHAR(50),
    merchant_name            VARCHAR(100),
    amount                   NUMERIC(19,4),
    currency                 VARCHAR(3),
    -- ACS Transaction ID (generated by this ACS, returned in ARes)
    acs_trans_id             UUID         NOT NULL UNIQUE,
    -- Directory Server Transaction ID (received in AReq)
    ds_trans_id              UUID,
    -- 3DS Server Transaction ID (from the merchant/3DS Server)
    threeds_server_trans_id  UUID,
    -- Current state of the authentication attempt
    status                   VARCHAR(30)  NOT NULL DEFAULT 'INITIATED'
                             CHECK (status IN ('INITIATED','CHALLENGE_REQUIRED',
                                               'AUTHENTICATED','FAILED','REJECTED')),
    -- Frictionless or Challenge
    authentication_type      VARCHAR(20)  CHECK (authentication_type IN ('FRICTIONLESS','CHALLENGE')),
    -- CAVV (Cardholder Authentication Verification Value) — populated on AUTHENTICATED
    authentication_value     VARCHAR(64),                -- Base64-encoded CAVV (~28 chars)
    -- ECI indicator: 05=authenticated, 06=frictionless attempt, 07=no auth
    eci_indicator            VARCHAR(2),
    -- Challenge metadata
    challenge_sent_at        TIMESTAMPTZ,
    challenge_attempts       SMALLINT     NOT NULL DEFAULT 0,
    authenticated_at         TIMESTAMPTZ,
    version                  BIGINT       NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_threeds_sessions_card_id      ON threeds_sessions(card_id);
CREATE INDEX idx_threeds_sessions_acs_trans_id ON threeds_sessions(acs_trans_id);
CREATE INDEX idx_threeds_sessions_status       ON threeds_sessions(status);

-- ── 3DS OTP Tokens ────────────────────────────────────────────────────────────
-- One OTP per challenge session. Single-use; expires after configurable window.
CREATE TABLE threeds_otp_tokens (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  UUID         NOT NULL REFERENCES threeds_sessions(id) ON DELETE CASCADE,
    otp_hash    VARCHAR(64)  NOT NULL,        -- HMAC-SHA256(otp, hmac_key) — never store plaintext
    expires_at  TIMESTAMPTZ  NOT NULL,
    verified    BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_threeds_otp_session ON threeds_otp_tokens(session_id);
