package com.cba.card.threeds;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "threeds_sessions")
@Getter @Setter @NoArgsConstructor
public class ThreeDsSession {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** FK to the card being authenticated. May be null if card lookup failed. */
    @Column(name = "card_id")
    private UUID cardId;

    @Column(name = "merchant_id", length = 50)
    private String merchantId;

    @Column(name = "merchant_name", length = 100)
    private String merchantName;

    @Column(precision = 19, scale = 4)
    private BigDecimal amount;

    @Column(length = 3)
    private String currency;

    /** Generated by this ACS on AReq receipt; returned in ARes. */
    @Column(name = "acs_trans_id", nullable = false, unique = true)
    private UUID acsTransId;

    /** From the Directory Server's AReq. */
    @Column(name = "ds_trans_id")
    private UUID dsTransId;

    /** From the 3DS Server / merchant's AReq. */
    @Column(name = "threeds_server_trans_id")
    private UUID threeDsServerTransId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private ThreeDsStatus status = ThreeDsStatus.INITIATED;

    /**
     * How this authentication was completed.
     * FRICTIONLESS = no cardholder interaction; CHALLENGE = OTP verified.
     */
    @Column(name = "authentication_type", length = 20)
    private String authenticationType;

    /** Base64-encoded CAVV; set when status → AUTHENTICATED. */
    @Column(name = "authentication_value", length = 64)
    private String authenticationValue;

    /**
     * ECI indicator:
     * <ul>
     *   <li>{@code 05} — fully authenticated (challenge completed)</li>
     *   <li>{@code 06} — attempted (frictionless)</li>
     *   <li>{@code 07} — not authenticated</li>
     * </ul>
     */
    @Column(name = "eci_indicator", length = 2)
    private String eciIndicator;

    @Column(name = "challenge_sent_at")
    private OffsetDateTime challengeSentAt;

    @Column(name = "challenge_attempts", nullable = false)
    private int challengeAttempts = 0;

    @Column(name = "authenticated_at")
    private OffsetDateTime authenticatedAt;

    @Version
    private long version;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt = OffsetDateTime.now();

    @PreUpdate
    void onUpdate() { this.updatedAt = OffsetDateTime.now(); }
}
