package com.cba.card.settlement;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Audit record for one settlement file transmission attempt to a scheme
 * clearinghouse network.
 *
 * <h3>Status lifecycle</h3>
 * <pre>
 *   PENDING → TRANSMITTED → ACKNOWLEDGED
 *           ↘ FAILED (retryable — attempt_count incremented on each try)
 * </pre>
 *
 * <p>A partial-retry invariant: a TRANSMITTED record is never overwritten.
 * If acknowledgement is missing (scheme did not send ACK), the record stays
 * TRANSMITTED and operations staff reconcile manually. This mirrors how
 * production scheme networks operate — file delivery confirmation and
 * settlement acknowledgement are separate concerns.
 */
@Entity
@Table(name = "settlement_transmissions")
@Getter @Setter @NoArgsConstructor
public class SettlementTransmission {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "batch_id", nullable = false)
    private UUID batchId;

    /** Card scheme: VISA, MASTERCARD, VERVE, AFRIGO, UNIONPAY. */
    @Column(nullable = false, length = 20)
    private String scheme;

    /** Scheme-mandated filename generated by {@link SettlementFileExporter#generateFileName}. */
    @Column(name = "file_name", nullable = false, length = 100)
    private String fileName;

    @Column(name = "record_count", nullable = false)
    private int recordCount;

    @Column(name = "total_amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal totalAmount = BigDecimal.ZERO;

    @Column(name = "settlement_date", nullable = false)
    private LocalDate settlementDate;

    /** SFTP or HTTPS */
    @Column(name = "transmission_method", nullable = false, length = 10)
    private String transmissionMethod = "SFTP";

    /** Scheme endpoint at the time of transmission (for audit trail). */
    @Column(length = 255)
    private String endpoint;

    /** PENDING → TRANSMITTED → ACKNOWLEDGED | FAILED */
    @Column(nullable = false, length = 20)
    private String status = "PENDING";

    @Column(name = "attempt_count", nullable = false)
    private int attemptCount = 0;

    @Column(name = "last_attempt_at")
    private OffsetDateTime lastAttemptAt;

    /** Timestamp when the file bytes were successfully delivered to scheme server. */
    @Column(name = "transmitted_at")
    private OffsetDateTime transmittedAt;

    /** Timestamp when the scheme sent an acknowledgement (not all schemes do this). */
    @Column(name = "acknowledged_at")
    private OffsetDateTime acknowledgedAt;

    /** Last failure reason — overwritten on each retry attempt. */
    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    @Version
    private long version;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt = OffsetDateTime.now();

    @PreUpdate
    void onUpdate() { this.updatedAt = OffsetDateTime.now(); }
}
